### ISSUE TITLE
Issue not covered in Unix-CLI Lesson plan.

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/unix-cli-assessment#65]
(2) Suppose that we're working on a project, and we want to use a font that's being hosted somewhere on the internet. Would we use an absolute or relative path to refer to it? Why?

**Comment by gaand** [comment]
I don't understand.

**Comment by RealWeeks** [comment]
@gaand I think he's saying the because it wasn't explicitly mentioned in that iteration of the lesson that that the devs wouldn't be able to make the connection to using it on a front end. 

I covered this in this iteration as a talking point, maybe an explicit mention in the unix-cli repository about pathing in development?

**Comment by payne-chris-r** [comment]
Exactly. We don't specifically call out whether files hosted on the internet are absolute or relative...

**Comment by RealWeeks** [comment]
@payne-chris-r I'm going to close this and link to it on the unix-cli repo.  I think addressing it there makes more sense.  Please reopen if you disagree.
